name: Compile PR Build

# Déclenchement du workflow
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup .NET (modifier selon ton projet)
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    # 3. Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # 4. Build le projet en Release
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # 5. Publish la build dans un dossier spécifique
    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    # 6. Zip le contenu du build
    - name: Create ZIP artifact
      run: |
        zip -r build.zip ./publish

    # 7. Upload l'artefact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-zip
        path: build.zip
