name: Build & Release Batocera-Ports

on:
  push:
    tags:
      - "v*"   # ex: v1.0.0, v2.3.4

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore batocera-ports.sln

    - name: Build solution (Release)
      run: msbuild batocera-ports.sln /p:Configuration=Release

    - name: Archive all build outputs
      shell: pwsh
      run: |
        $zipPath = "batocera-ports-${{ github.ref_name }}.zip"
        $releaseDirs = Get-ChildItem -Path . -Recurse -Include Release -Directory | Where-Object { $_.FullName -match "\\bin\\Release$" }
        $tempDir = "all-builds"
        New-Item -ItemType Directory -Force -Path $tempDir | Out-Null
        foreach ($dir in $releaseDirs) {
          $projectName = Split-Path (Split-Path $dir.FullName -Parent) -Leaf
          $dest = Join-Path $tempDir $projectName
          Copy-Item -Path "$($dir.FullName)\*" -Destination $dest -Recurse -Force
        }
        Compress-Archive -Path "$tempDir\*" -DestinationPath $zipPath -Force
        echo "ZIP_PATH=$zipPath" >> $env:GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ZIP_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
