name: Build PR and Zip

# Déclenchement sur pull request vers main ou master
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build-and-zip:
    runs-on: windows-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 3. Installer NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # 4. Restaurer les packages NuGet
      - name: Restore NuGet packages
        run: nuget restore batocera-ports.sln

      # 5. Compiler le projet en Release
      - name: Build solution (Release)
        run: msbuild batocera-ports.sln /p:Configuration=Release /m

      # 6. Créer un ZIP du dossier Release
      - name: Create ZIP of Release folder
        run: |
          powershell Compress-Archive -Path 'batocera-ports\bin\Release\*' -DestinationPath 'batocera-ports-PR.zip'

      # 7. Upload du ZIP comme artifact
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: batocera-ports-PR
          path: batocera-ports-PR.zip
